export const ADD_TODO_LOADING="ADD_TODO_LOADING";
export const ADD_TODO_SUCCESS="ADD_TODO_SUCCESS";
export const ADD_TODO_ERROR="ADD_TODO_ERROR";
export const GET_TODO_LOADING="GET_TODO_LOADING";
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS";
export const GET_TODO_ERROR="GET_TODO_ERROR";

export const PATCH_TODO_LOADING="PATCH_TODO_LOADING";
export const PATCH_TODO_SUCCESS="PATCH_TODO_SUCCESS";
export const PATCH_TODO_ERROR="PATCH_TODO_ERROR";

export const DELETE_TODO_LOADING="DELETE_TODO_LOADING";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS";
export const DELETE_TODO_ERROR="DELETE_TODO_ERROR";